### ISSUE TITLE
Hardcoded default region, confusing behaviour

### ISSUE THREAD

**Issue by pmazurek** [HexmosTech/aws_sqs_consumer_python#3]
Hey,

I've just had a bit of confusing behaviour where this package would claim my queue does not exist

 ```botocore.errorfactory.QueueDoesNotExist: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the ReceiveMessage operation: The specified queue does not exist for this wsdl version.```

while I was completely positive it exists.

Turns out it ignores the default region set by environment/boto and instead quietly although merrily defaults to hardcoded ''eu-west-1" :shrug: 

Fixed in https://github.com/HexmosTech/aws_sqs_consumer_python/pull/4

**Comment by shrsv** [comment]
Thanks for the bug report and PR. I've made relevant changes to honor the region env var and made a new release at [pypi](https://pypi.org/project/aws-sqs-consumer/0.0.15/)
